name: Tests

on:
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install deps and start server
        run: |
          make bootstrap
          make background
      - name: Lint code
        run: make lint
      - uses: matt-ball/newman-action@0.1.7
        with:
          collection: postman_collection.json
          environment: postman_environment.json
